    <?php $page = 'home';
    include('menu_topo.phtml'); ?>
    <div class="container mt-4">
        <form id="agendar_paciente" method="post" action="confirma_agendamento">
            <input name="agendado_por" type='hidden' value=<?= $_SESSION['id'] ?>>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputEmail4">Paciente</label>
                    <input name="paciente" type="text" class="form-control" id="Paciente" placeholder="Paciente">
                </div>
                <div class="form-group col-md-6">
                    <label for="sus">Cartão do SUS</label>
                    <input type="text" name="sus" class="form-control sus" placeholder="SUS" id="sus">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-7">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <label class="input-group-text" for="inputGroupSelect01">Médico</label>
                        </div>
                        <select name="medico_id" class="custom-select" id="medico">

                        </select>
                    </div>
                </div>
                <div class="form-group col-md-2">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <label class="input-group-text" for="inputGroupSelect01">Horário</label>
                        </div>
                        <select name="horario" class="custom-select" id="horario">

                        </select>
                        <input type="hidden" name="atendimentos" id="atendimentos">
                    </div>
                </div>
                <div class="form-group col-md-3">
                    <input name="prontuario" type="text" class="form-control prontuario" id="prontuario" placeholder="Prontuário" onsubmit="formatarCampos()">
                </div>
            </div>

            <div class="d-flex justify-content-center" id='dias_disponiveis'>

            </div>
            <input type="hidden" id='dia_semana' />

            <div id="calendario">
                <div id="calendar"></div>
                <input type="hidden" id='dia' class="dataCompleta" name="dia">
            </div>
            <div class="form-row justify-content-center mt-4">
                <button type="submit" form="agendar_paciente" class="btn btn-primary">Agendar Paciente</button>
            </div>
        </form>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="container-fluid" id="mensagem_modal">
                        Add rows here
                    </div>
                </div>
                <form id="form_confirmacao">
                    <div class="modal-footer">
                        <input type="hidden" id="save_data" name="save_data">
                        <input type="hidden" id="status" name="status">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Voltar</button>
                        <button id="button_confirmacao" type="submit" class="btn btn-primary">Salvar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="../js/ajustesCalendario.js"></script>

    <script>
        $(window).on("load", function() {
            listamedicos()
        });


        let lista_medicos = []

        function listamedicos() {
            $.get("/lista_medicos",
                function(medicos, textStatus, response) {
                    (medicos.map(function(medico, index) {
                        medico.turnos = JSON.parse(medico.turnos)
                    }))
                    lista_medicos = medicos
                    const diasDivArray = document.querySelectorAll('.day')

                    medicos.forEach(function(medico, index) {
                        $('#medico').append(`<option value='${medico.id}'>${medico.nome}</option>`)
                        if (medico.id === document.querySelector('#medico').value) {
                            medico.turnos.forEach(function(turno, index) {
                                $('#horario').append(`<option value='${turno.horario_id}'>${turno.horario_label}</option>`)
                                if (turno.horario_id === document.getElementById('horario').value) {
                                    let diasSemanaMedico = []
                                    turno.dias.forEach((dia, index) => {
                                        diasSemanaMedico.push(parseInt(dia.dia))
                                    });

                                    let diasDisponiveis = [...diasDivArray].filter(n => diasSemanaMedico.indexOf(formatDate(n.dataset.dateVal).getDay()) > -1)

                                    turno.dias.filter(function(dia) {
                                        let div = diasDisponiveis.filter(div => parseInt(formatDate(div.dataset.dateVal).getDay()) === parseInt(dia.dia))
                                        $(div).attr('atendimentos', parseInt(dia.atendimentos));
                                    })

                                    diasDisponiveis.forEach(function(node){
                                        countAtendimentos(medico.id, node.dataset.dateVal, function (count) {
                                            node.attributes.atendimentos.value = parseInt(node.attributes.atendimentos.value) - parseInt(count)
                                            if(parseInt(node.attributes.atendimentos.value) <= 0) {
                                                node.style = 'background-color: #de7e6a; color: white; pointer-events: none;'
                                            }
                                        })
                                    })

                                    diasDivArray.forEach(node => node.style = 'pointer-events: none;')
                                    diasDisponiveis.forEach(node => node.style = 'background-color : #6aa0f1;   color: white;')
                                }
                            })
                        }
                    })
                },
                "json"
            );
        }

        $('#medico').change(function(e) {
            e.preventDefault();
            $('#horario').html('')
            $('#dias_disponiveis').html('')
            lista_medicos.forEach(function(medico, index) {
                if (medico.id === document.querySelector('#medico').value) {
                    const diasDivArray = document.querySelectorAll('.day')
                    medico.turnos.forEach(function(turno, index) {
                        $('#horario').append(`<option value='${turno.horario_id}'>${turno.horario_label}</option>`)
                        if (turno.horario_id === document.getElementById('horario').value) {
                            let diasSemanaMedico = []
                            turno.dias.forEach((dia, index) => {
                                diasSemanaMedico.push(parseInt(dia.dia))
                            });

                            let diasDisponiveis = [...diasDivArray].filter(n => diasSemanaMedico.indexOf(formatDate(n.dataset.dateVal).getDay()) > -1)

                            turno.dias.filter(function(dia) {
                                let div = diasDisponiveis.filter(div => parseInt(formatDate(div.dataset.dateVal).getDay()) === parseInt(dia.dia))
                                $(div).attr('atendimentos', dia.atendimentos);
                            })

                            diasDisponiveis.forEach(function(node){
                                countAtendimentos(medico.id, node.dataset.dateVal, function (count) {
                                    node.attributes.atendimentos.value = parseInt(node.attributes.atendimentos.value) - parseInt(count)
                                    if(parseInt(node.attributes.atendimentos.value) <= 0) {
                                        node.style = 'background-color: #de7e6a; color: white; pointer-events: none;'
                                    }
                                })
                            })

                            diasDivArray.forEach(node => node.style = 'pointer-events: none;')
                            diasDisponiveis.forEach(node => node.style = 'background-color : #6aa0f1;  color: white;')

                            //Deixa o dia em vermelho, caso o valor fique abaixo de zero
                            desabilitarAtendimentosAbaixoDeZero(diasDisponiveis)
                        }
                    })
                }
            })
        });

        $('#calendar').on('selectMonth', function(event, month, newMonth, ) {
            mostraDiasDisponiveis()
        })

        $('#horario').change(function(e) {
            e.preventDefault();
            mostraDiasDisponiveis()
        });

        function mostraDiasDisponiveis() {
            $('#dias_disponiveis').html('')
            const diasDivArray = document.querySelectorAll('.day')
            lista_medicos.forEach(function(medico, index) {
                if (medico.id === document.querySelector('#medico').value) {
                    medico.turnos.forEach(function(turno, index) {
                        if (turno.horario_id === document.getElementById('horario').value) {
                            let diasSemanaMedico = []
                            turno.dias.forEach((dia, index) => {
                                diasSemanaMedico.push(parseInt(dia.dia))
                            });
                            let diasDisponiveis = [...diasDivArray].filter(n => diasSemanaMedico.indexOf(formatDate(n.dataset.dateVal).getDay()) > -1)

                            diasDisponiveis.forEach(function(node){
                                countAtendimentos(medico.id, node.dataset.dateVal, function (count) {
                                    node.attributes.atendimentos.value = parseInt(node.attributes.atendimentos.value) - parseInt(count)
                                    if(parseInt(node.attributes.atendimentos.value) <= 0) {
                                        node.style = 'background-color: #de7e6a; color: white; pointer-events: none;'
                                    }
                                })
                            })

                            diasDivArray.forEach(node => node.style = 'pointer-events: none;')
                            diasDisponiveis.forEach(node => node.style = 'background-color : #6aa0f1;  color: white;')
                        }
                    })
                }
            })
        }

        function countAtendimentos(medico_id, dia, handleData){
             $.ajax({
                    type: "get",
                    url: "contar_agendamentos",
                    data: {dia:dia, medico_id: medico_id},
                    dataType: "json",
                    success: function (response) {
                        handleData(parseInt(response[0]))
                    }
            });
        }

        function desabilitarAtendimentosAbaixoDeZero(nodes) {
            nodes.forEach(function(node) {
                if (typeof node.attributes.atendimentos !== 'undefined') {
                    if (node.attributes.atendimentos.value <= 0) {
                        $(node).addClass('bg-danger');
                    }
                }
            })
        }

        $('#agendar_paciente').submit(function(e) {
            e.preventDefault();
            $("#save_data").val('');
            $("#status").val('');
            $.ajax({
                type: "POST",
                url: "/confirma_agendamento",
                data: $(this).serialize(),
                dataType: "json",
                success: function(response) {
                    $('#mensagem_modal').html(response.mensagem);
                    $('#modelId').modal('show');
                    if (response.status != 2) {
                        $('#button_confirmacao').show();
                        $('.modal-title').html('Confirma a inserção?');
                        $('.modal-title').addClass('text-primary');
                        $("#save_data").attr('value', JSON.stringify(response.post));
                        $("#status").attr('value', response.status);
                        mostraDiasDisponiveis()
                    } else if (response.status == 2) {
                        $('#button_confirmacao').hide();
                        $('.modal-title').html('Erro no agendamento!');
                        $('.modal-title').addClass('text-danger');
                        mostraDiasDisponiveis()
                    }
                }
            });
        });

        $('#form_confirmacao').submit(function(e) {
            e.preventDefault();
            $.ajax({
                type: "POST",
                url: "/agendaPaciente",
                data: $(this).serialize(),
                dataType: "json",
                success: function(response) {
                    $('#mensagem_modal').html(response.mensagem);
                    $('#modelId').modal('show');
                    $('.modal-title').html('Sucesso!');
                    $('.modal-title').addClass('text-success');
                    $('#button_confirmacao').hide();
                    limpaCampos();
                }
            });
        });

        function limpaCampos() {
            $('#Paciente').val('');
            $('#sus').val('');
            $('#prontuario').val('');
        }

        let inputPaciente = new Cleave('.prontuario', {
            numeralDecimalMark: ',',
            delimiter: '.',
            numeral: true,
            numeralThousandsGroupStyle: 'thousand'
        });

        let inputSus = new Cleave('#sus', {
            blocks: [3, 4, 4, 4]
        });
    </script>