<?php $page = 'agendaDia';
include('menu_topo.phtml') ?>

<div class="container">
    <div class="row mt-4">
        <div class="col-md-12">
            <h1 class="display-4 text-center">
                Selecione o agendamento do dia desejado
            </h1>
        </div>
    </div>

    <form id="formButtons" method='get'></form>

    <form id='formBusca' method="post" action="filtra_agenda">
        <div class="row mt-4">
            <div class="col-md-8">
                <input class="form-control" type="text" name="paciente" id="paciente" placeholder="paciente">
            </div>
            <div class="col-md-4 mt-2 mt-md-0">
                <input class="form-control" type="text" name="prontuario" id="prontuario" placeholder="prontuario">
            </div>
        </div>

        <div class="row mt-3 justify-content-between">
            <div class="col-md-6">
                <div class="input-group mb-2">
                    <div class="input-group-prepend">
                        <div class="input-group-text">Medico</div>
                    </div>
                    <select name="medico" id="medico" class="form-control">
                        <option value="">--------------------------------</option>
                    </select>
                </div>
            </div>
            <div class="col-md-2">
                <select name="horario" id="horario" class="form-control">
                    <option value="">-----------------------------------------------</option>
                </select>
            </div>
            <div class="col-md-3 mt-2 mt-md-0">
                <input class="form-control" type="date" name="dia" id="dia">
            </div>
            <div class="col-md-1 text-center mt-2 mt-md-0">
                <button class="form-control bg-primary text-white" type="submit">busca</button>
            </div>
        </div>
        <input id='page' type="hidden" name="page" value='1'>
    </form>

    <div class="table-responsive mt-2">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Dia</th>
                    <th>Prontuario</th>
                    <th>Paciente</th>
                    <th>Medico</th>
                    <th>Horario</th>
                    <th>Agendado por:</th>
                    <th>Atendimento</th>
                    <th>Cancelamento</th>
                </tr>
            </thead>
            <tbody id='relatorio_agendados'>

            </tbody>
        </table>
    </div>
</div>

<div class="d-flex flex-wrap justify-content-center mt-5">
    <nav aria-label="Page navigation example ">
        <ul class="pagination d-flex flex-wrap justify-content-center" id='pagination'>

        </ul>
    </nav>
</div>

<!-- Modal -->
<div class="modal fade" id="modalConfirmacao" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-danger" id="modalConfirmacaoLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-success" id='botaoExclusao'>Sim, quero excluir</button>
            </div>
        </div>
    </div>
</div>

<!-- Toast --->

<div aria-live="polite" aria-atomic="true" class="d-flex justify-content-center align-items-center" style="height: 200px;">

    <!-- Then put toasts within -->
    <div id='liveToast' class="toast" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header">
            <img src="..." class="rounded mr-2" alt="...">
            <strong class="mr-auto">Bootstrap</strong>
            <small>11 mins ago</small>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="toast-body">
            Hello, world! This is a toast message.
        </div>
    </div>
</div>



<script>
    let medicos = []
    let agendamentos = []

    $(window).on("load", function() {
        getMedicos();
        $('#formBusca').submit();
    });



    $('#medico').change(function(e) {
        e.preventDefault();
        $('#horario').select().html('');
        let medicoSelecionado = document.getElementById('medico').selectedIndex
        let horarios = JSON.parse(medicos[medicoSelecionado].turnos)
        if (medicoSelecionado !== 0) {
            horarios.map(option => $('#horario').append(`<option value='${option.horario_id}'>${option.horario_label}</option>`))
        } else {
            $('#horario').append(`<option value=''>---------------</option>`);
        }
    });

    function getMedicos() {
        $.ajax({
            type: "GET",
            url: "/lista_medicos",
            dataType: "json",
            success: function(response) {
                medicos.push(...response)
                medicos.map(option => $('#medico').append(`<option value='${option.id}'>${option.nome}</option>`))
                $('#medico').change()
            }
        });
    }

    function changePage(id) {
        $('#page').val(id);
        $('#formBusca').submit();
    }

    $('#formBusca').submit(function(e) {
        e.preventDefault()
        $('#relatorio_agendados').html('')

        $.ajax({
            type: "post",
            url: "/filtra_agenda",
            data: $(this).serialize(),
            dataType: "json",
            success: function(response) {
                renderRow(response.agendamentos)
                $('#pagination').html(response.links);
                $('#page').val(1);
            }
        });
    });

    function deletarAgendamento(id) {

        var confirmado = false
        console.log(confirmado)

        $('#modalConfirmacao .modal-body').html('Tem certeza de que quer cancelar esta consulta? Essa Alteração não pode ser desfeita.')
        $('#modalConfirmacaoLabel').html('Confirma a Exclusão do Agendamento?')
        $('#modalConfirmacao').modal('show')

        $('#botaoExclusao').click(function(e) {
            confirmado = true
            console.log(confirmado)
            $('#modalConfirmacao').modal('hide')

            if (confirmado == true) {
                $.ajax({
                    type: "get",
                    url: "/cancelar_agendamento",
                    data: 'action=delete&id=' + id,
                    dataType: "json",
                    success: function(response) {
                        $('#liveToast').toast('show')
                        $('#formBusca').submit();
                        confirmado = false
                    }
                });
            }
        })
    }


    function atualizarAgendamento(id) {
        $.ajax({
            type: "get",
            url: "atender_paciente",
            data: {
                action: 'atender',
                id: id
            },
            dataType: "json",
            success: function(response) {
                $('#formBusca').submit();
            }
        });
    }

    function renderRow(dataList) {
        dataList.forEach(data => {
            let tr = '<tr>'
            tr += `<td>${data.dia}</td>`
            tr += `<td>${data.prontuario}</td>`
            tr += `<td>${data.paciente}</td>`
            tr += `<td>${data.medico}</td>`
            tr += `<td>${data.horario}</td>`
            tr += `<td>${data.agendado_por}</td>`
            tr += `<td>`
            tr += `<button onclick='atualizarAgendamento(${data.id})' class='btn btn-${(data.atendimento_realizado !== "0") ? "info" : "success"}'>`
            tr += (data.atendimento_realizado !== "0") ? "Atendido" : "Atender"
            tr += `</button></td>`
            tr += `<td><button onclick='deletarAgendamento(${data.id})' class='btn btn-danger'>Cancelar</button></td>`

            tr += '</tr>'
            $('#relatorio_agendados').append(tr);
        })
    }

    function renderPagination(dataList) {
        dataList.forEach(function(data) {
            let li = `<li></li>`
        })
    }

    let inputPaciente = new Cleave('#prontuario', {
        numeralDecimalMark: ',',
        delimiter: '.',
        numeral: true,
        numeralThousandsGroupStyle: 'thousand'
    });

    let inputSus = new Cleave('#sus', {
        blocks: [3, 4, 4, 4]
    });
</script>