



    <?php $page = 'cadastrarFuncionario'; include_once('menu_topo.phtml'); ?>

    <!-- Button trigger modal -->

    <div class="container mt-4">

        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">

            Cadastrar Funcionário

        </button>



        <!-- Modal -->



        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"

            aria-hidden="true">

            <div class="modal-dialog" role="document">

                <div class="modal-content">

                    <div class="modal-header">

                        <h5 class="modal-title" id="exampleModalLabel">Cadastro de funcionário</h5>

                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">

                            <span aria-hidden="true">&times;</span>

                        </button>

                    </div>

                    <div class="modal-body">



                        <form id="form_cadastro">

                            <div class="form-row">

                                <div class="form-group col-md-6">

                                    <label for="inputEmail4">Email</label>

                                    <input name="email" type="email" class="form-control" id="inputEmail4"

                                        placeholder="Email">

                                </div>

                                <div class="form-group col-md-6">

                                    <label for="inputPassword4">Senha</label>

                                    <input name="senha" type="password" class="form-control" id="inputPassword4"

                                        placeholder="Password">

                                </div>

                            </div>

                            <div class="form-group">

                                <label for="nomeCompleto">Nome Completo</label>

                                <input name="nome" type="text" class="form-control"

                                    placeholder="Insira o nome do funcionário">

                            </div>



                            <div class="form-row">

                                <div class="form-group col-md-6">

                                    <label for="telefone">Telefone</label>

                                    <input name="telefone" type="text" class="form-control input_phone"

                                        placeholder="Telefone">

                                </div>



                                <div class="form-group col-md-6">

                                    <label for="setor">Setor</label>

                                    <select class="form-control" name="id_setor">

                                        <?php foreach ($this->view->setores as $key => $setor) {?>

                                        <option value=<?=$setor['id']?>><?=$setor['setor']?></option>

                                        <?php }?>

                                    </select>

                                </div>

                            </div>

                        </form>

                        <form id="form_arquivo" enctype="multipart/form-data" method="post" action="/upload_foto">

                            <div class="mb-3">

                                <label for="formFile" class="form-label">Foto de perfil</label>

                                <input class="form-control" name="arquivo" type="file" id="formFile">

                            </div>

                        </form>

                        <button form="form_cadastro" type="submit" class="btn btn-primary">Cadastrar</button>

                    </div>

                </div>

            </div>

        </div>

    </div>

    <!----------------------Fim Modal Cadastro---------------------------->

    <div class="container mt-4">

        <table class="table">

            <thead>

                <tr>

                    <th scope="col"><button class="btn btn-sm"><i class="fa fa-fw fa-sort"

                                style="color: Dodgerblue;"></button></i>#</th>

                    <th scope="col"><button class="btn btn-sm"><i class="fa fa-fw fa-sort"

                                style="color: Dodgerblue;"></button></i>Nome</th>

                    <th scope="col"><button class="btn btn-sm"><i class="fa fa-fw fa-sort"

                                style="color: Dodgerblue;"></button></i>E-mail</th>

                    <th scope="col"><button class="btn btn-sm"><i class="fa fa-fw fa-sort"

                                style="color: Dodgerblue;"></button></i>Telefone</th>

                    <th scope="col"><button class="btn btn-sm"><i class="fa fa-fw fa-sort"

                                style="color: Dodgerblue;"></button></i>Setor</th>

                    <th scope="col"></th>

                </tr>

            </thead>

            <tbody id="tabela">



            </tbody>

        </table>

    </div>





<script>

//essa rotina acontece quando o cadastro é realizado

var armazenaIds = []

$("#form_cadastro").submit(function(e) {

    e.preventDefault();

    $('#form_arquivo').submit();

    $('#exampleModal').modal('toggle');

    $.ajax({

        type: "POST",

        url: "funcionario_cadastrado",

        data: $(this).serialize(),

        dataType: "json",

        success: function(response) {

            listarRegistros();

        }

    });

});



$(document).ready(function() {

    listarRegistros();

});



$('#form_arquivo').submit(function (e) { 

    e.preventDefault();

});





function listarRegistros() {

   

    $.getJSON("lista_funcionarios", function(response) {

        $("#tabela").html('');

        response.forEach(function(r, index) {

             //console.log(r)

            let deleteButton = '\n' +

                '<td>\n' +

                '<button onclick="deletar_funcionario(' + r['id'] + ')" id="botao_delete_' + r['id'] +

                '" class="btn btn-sm btn-primary">\n' +

                '<i class="fas fa-trash-alt"></i>\n' +

                '</button>\n' +

                '</td>'





            let row = '<tr><th scope="row">' + (index + 1) + '</th><td>' + r['nome'] +

                '</td><td>' + r['email'] + '</td><td>' + r['telefone'] + '</td><td>' +

                r['setor'] + '</td><td>' + deleteButton + '</td></tr>';



            $("#tabela").append(row);

        });

    });

}



function deletar_funcionario(id) {



    $.get("/acao?action=delete&id=" + id, function(data) {

        listarRegistros();

    });

}





</script>