<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#"><img src="img/logo_cardoso_fontes.gif" height="60px" alt="" loading="lazy"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav  ml-auto text-right">
        <a href="/agenda_paciente" class="nav-link <?php if($page == 'home'){echo 'btn-primary text-white';}?> btn-sm align-self-center px-2"
                value="0">Agendar Consulta</a>
                <a href="/cadastrar_prontuario" class="nav-link <?php if($page == 'cadastrar_prontuario'){echo 'btn-primary text-white';}?> btn-sm text-nowrap align-self-center px-2"
                value="0">Cadastrar Prontuário</a>
                <a href="/agenda_dia" class="nav-link btn-sm <?php if($page == 'agendaDia'){echo 'btn-primary text-white';}?> text-nowrap align-self-center px-2"
                value="1">Visualizar Agenda do dia</a>
                <a href="/relatorio_atendidos"
                class="nav-link btn-sm <?php if($page == 'relatorio'){echo 'btn-primary text-white';}?> text-nowrap align-self-center px-2"
                value="1">Relatório de atendimentos</a>
                <?php if(isset($_SESSION['setor']) && $_SESSION['setor'] == 'Diretoria'){?>
                <a href="/cadastra_funcionario"
                class="nav-link btn-sm <?php if($page == 'cadastrarFuncionario'){echo 'btn-primary text-white';}?> text-nowrap align-self-center px-2"
                value="3">Cadastrar Funcionário</a>
                <?php }?>
                <?php if(isset($_SESSION['setor']) && $_SESSION['setor'] != 'Diretoria'){?>
                <a href="/configurar_conta"
                class="nav-link btn-sm <?php if($page == 'configurarDados'){echo 'btn-primary text-white';}?> text-nowrap align-self-center px-2"
                value="3">Alterar Informaçoes pessoais</a>
                <?php }?>
                <div class="d-flex flex-column align-items-center">
                <i class="fa fa-user-circle btn-lg text-primary" aria-hidden="true"></i>
                <p class="text-primary"><?=$_SESSION['nome']?></p>
                </div>
                <a href="/sair" class="nav-link btn" value="4" class=" d-flex flex-column align-items-center"><div>Sair</div><i class="pl-2 fas fa-sign-out-alt"></i></a>
    </div>
    </div>
</nav>
