<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#"><img src="img/logo_cardoso_fontes.gif" height="60px" alt="" loading="lazy"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav  ml-auto text-right">

            <!--=====================================================button group 1=================================================================-->
            <div class="btn-group-vertical align-self-center">
                <div class="nav-link btn-sm <?php if($page == 'home' || $page == 'agendaDia'){echo 'btn-primary text-white';}?> text-nowrap align-self-center px-2  dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    <?php if($page == 'home'){
                        echo 'Agendar consulta';
                    }else if($page == 'agendaDia'){
                        echo 'Agendamento do dia';}else{
                            echo 'Agenda';
                        }?>
                </div>
                <div class="dropdown-menu">
                    <a href="/agenda_paciente" class="nav-link <?php if($page == 'home'){echo 'btn-primary text-white';}?> btn-sm align-self-center px-2" value="0">Agendar Consulta</a>
                    <a href="/agenda_dia"
                class="nav-link btn-sm <?php if($page == 'agendaDia'){echo 'btn-primary text-white';}?> text-nowrap align-self-center px-2"
                value="1">Visualizar Agenda do dia</a>
                </div>
            </div>
        <!--================================================================================================================================================-->


        <!--=====================================================button group 2=================================================================-->
            <div class="btn-group-vertical align-self-center">
                <div class="nav-link btn-sm <?php if($page == '(Cadastro)' || $page == '(Pesquisa)'){echo 'btn-primary text-white';}?> text-nowrap align-self-center px-2  dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    Prontuário <?php if($page == '(Cadastro)' || $page == '(Pesquisa)'){echo $page;}?>
                </div>
                <div class="dropdown-menu">
                    <a class="dropdown-item <?php if($page == '(Cadastro)'){echo 'active';}?>" href="/cadastrar_prontuario">Cadastro</a>
                    <a class="dropdown-item <?php if($page == '(Pesquisa)'){echo 'active';}?>"  href="/pesquisar_prontuario">Pesquisa</a>
                </div>
            </div>
        <!--================================================================================================================================================-->

            <a href="/relatorio_atendidos"
                class="nav-link btn-sm <?php if($page == 'relatorio'){echo 'btn-primary text-white';}?> text-nowrap align-self-center px-2"
                value="1">Relatório de atendimentos</a>
            <?php if(isset($_SESSION['setor']) && $_SESSION['setor'] == 'Diretoria'){?>
            <a href="/cadastra_funcionario"
                class="nav-link btn-sm <?php if($page == 'cadastrarFuncionario'){echo 'btn-primary text-white';}?> text-nowrap align-self-center px-2"
                value="3">Cadastrar Funcionário</a>
            <?php }?>
            <?php if(isset($_SESSION['setor']) && $_SESSION['setor'] != 'Diretoria'){?>
            <a href="/configurar_conta"
                class="nav-link btn-sm <?php if($page == 'configurarDados'){echo 'btn-primary text-white';}?> text-nowrap align-self-center px-2"
                value="3">Alterar Informaçoes pessoais</a>
            <?php }?>
            <div class="d-flex flex-column align-items-center">
                <i class="fa fa-user-circle btn-lg text-primary" aria-hidden="true"></i>
                <p class="text-primary"><?=$_SESSION['nome']?></p>
            </div>
            <a href="/sair" class="nav-link btn" value="4" class=" d-flex flex-column align-items-center">
                <div>Sair</div><i class="pl-2 fas fa-sign-out-alt"></i>
            </a>
        </div>
    </div>
</nav>