<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <a class="navbar-brand" href="#">
        <img src="img/logo_cardoso_fontes.gif" width="50%" height="50%" alt="" loading="lazy">
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler"
        aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <ul class="nav collapse navbar-collapse nav-pills d-md-flex flex-md-nowrap justify-content-start justify-content-md-end mt-4 mt-md-0"
        id="navbarToggler">
        <li class="nav-item">
            <a href="/agenda_paciente" class="nav-link <?php if($page == 'home'){echo 'btn-primary';}?> btn text-nowrap"
                value="0">Agendar Consulta</a>
        </li>
        <li class="nav-item">
            <a href="/agenda_dia" class="nav-link btn <?php if($page == 'agendaDia'){echo 'btn-primary';}?> text-nowrap"
                value="1">Visualizar Agenda do dia</a>
        </li>

        <li class="nav-item">
            <a href="/relatorio_atendidos"
                class="nav-link btn <?php if($page == 'relatorio'){echo 'btn-primary';}?> text-nowrap"
                value="1">Relatório de atendimentos</a>
        </li>

        <?php if(isset($_SESSION['setor']) && $_SESSION['setor'] == 'Diretoria'){?>
        <li class="nav-item">
            <a href="/cadastra_funcionario"
                class="nav-link btn <?php if($page == 'cadastrarFuncionario'){echo 'active';}?> text-nowrap"
                value="3">Cadastrar Funcionário</a>
        </li>
        <?php }?>
        <li class="ml-4">
            <img class="rounded-circle img-thumbnail">
            <p><?=$_SESSION['nome']?></p>
        </li>
        <li class="nav-item ml-4">
            <a href="/sair" class="nav-link btn" value="4">Sair<i class="pl-2 fas fa-sign-out-alt"></i></a>
        </li>
    </ul>
</nav>