<?php $page = '(Pesquisa)';
require_once('menu_topo.phtml');
?>

<form class="container mb-auto  align-items-center" id="pesquisar_prontuario">
    <div class="form-row">
        <div class="col-md-7 mt-3">
            <label for="nome">Nome:</label>
            <input type="text" id="nome" class="form-control" name="nome">
        </div>

        <div class="col-md-3 mt-3">
            <label for="sus">Sus:</label>
            <input type="text" id="sus" class="form-control" name="sus">
        </div>

        <div class="col-md-2 mt-3">
            <label for="prontuario">Prontuário:</label>
            <input type="text" id="prontuario" class="form-control" name="prontuario">
        </div>
    </div>

    <div class="form-row">
        <div class="col-md-6 mt-3">
            <label for="pai">Nome do pai:</label>
            <input type="text" id="pai" class="form-control" name="nome_pai">
        </div>

        <div class="col-md-6 mt-3">
            <label for="mae">Nome da mãe:</label>
            <input type="text" id="mae" class="form-control" name="nome_mae">
        </div>
    </div>

    <div class="row justify-content-center">
        <button type="submit" form="pesquisar_prontuario" class="btn btn-primary mt-3">Pesquisar</button>
    </div>
</form>

<form target="_blank" id='impressao' action='/imprimir_prontuario' method="POST">
    <!--<button type='submit'>clique aqui</button>-->
</form>

<div class="container mt-5 table-responsive-sm">
    <table class="table table-bordered">
        <thead class="thead-light">
            <tr>
                <th width="5%" scope="col">Prontuario</th>
                <th scope="col">Nome</th>
                <th scope="col">Sus</th>
                <th scope="col">Telefone</th>
                <th width="5%" scope="col">Impressão</th>
                <th width="5%" scope="col">Apagar</th>
            </tr>
        </thead>
        <tbody id="tabela">

        </tbody>
    </table>
</div>

<div class="d-flex flex-wrap justify-content-center mt-5">
    <nav aria-label="Page navigation example">
        <ul class="pagination d-flex flex-wrap justify-content-center">

        </ul>
    </nav>
</div>


<!-- Modal impressão-->
<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!--<object type="application/pdf" data="img/teste.pdf" width="100%" height="500" style="height: 85vh;">No Support</object>-->
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <h1>Policlínica cardoso fontes</h1>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>

<script>
var pagina = 1;

function changePage(pagina_clicada) {
    pagina = pagina_clicada;
    $('#pesquisar_prontuario').submit();
}

$('#pesquisar_prontuario').submit(function(e) {
    e.preventDefault();

    let nome = $('#nome').val();
    let sus = $('#sus').val();
    let prontuario = $('#prontuario').val();
    let pai = $('#pai').val();
    let mae = $('#mae').val();

    $.ajax({
        type: "post",
        url: "/realizar_pesquisa_prontuario",
        data: {
            nome: nome,
            sus: sus,
            prontuario: prontuario,
            nome_pai: pai,
            nome_mae: mae,
            pagina: pagina
        },
        dataType: "json",
        success: function(responses) {
            let tabela = $('#tabela').select();
            //console.log(responses)
            $(tabela).html('');
            $('.pagination').html(responses['links']); //botoes de paginacao
            responses[0].forEach(response => {
                let tr = createRow(response.prontuario, response.nome, response.sus,
                    response.telefone, response.id);

                $(tabela).append(tr);
            });
        }
    });
});

$(document).ready(function() {
    $('#pesquisar_prontuario').submit();
});


function createRow(prontuario, nome, sus, telefone, id) {
    //criar a tr e fazer o append no tbody
    //console.log(id)
    let tr = '<tr>'
    tr += '<td>' + prontuario + '</td>'
    tr += '<td>' + nome + '</td>'
    tr += '<td>' + sus + '</td>'
    tr += '<td>' + telefone + '</td>'
    tr += '<td class="text-center"><button class="btn icon-primary" id="botaoImpressao'+id+'" type="submit" form="impressao" name="paciente_id" value="'+id+'"><i class="fa fa-print btn icon-primary"></i></button></td>'
    tr += '<td class="text-center"><i class="fa fa-trash btn icon-primary" onclick="deleteProntuario(' + id +
        ')" aria-hidden="true"></i></td>'
    tr += '</tr>'
    return tr;
}

function deleteProntuario(id) {
    $.get("/acao?action=delete&id=" + id + "&dado=prontuario", function() {
        $('#pesquisar_prontuario').submit();
    });
}


</script>