<div class="d-flex justify-content-center" id="pront">
    <div class="folha-impressao bg-light d-flex flex-column" id="pront" style="width: 590px; height:840px;">

        <div class="d-flex justify-content-between">
            <div class="col-md-4 col-md-5 p-4 mt-3 ml-4 border border-dark rounded">
                <img src="img/logo_sus.jpg" alt="" height="50px">
            </div>

            <div class="col-md-4 p-1 mt-3 mr-4 border border-dark rounded">
                <div class="mr-auto ml-2 flex-1 pt-3" style="line-height:.8em; text-align:end">
                    <h6 style="font-size:.8em;">
                        Secretaria de Estado de Saúde
                    </h6>
                    <h6 style="font-size:.8em;">
                        Policlínica Cardoso Fontes
                    </h6>
                    <h6 style="font-size:.6em;">
                        Referência em pneumologia sanitária
                    </h6>
                </div>
            </div>
        </div>
        <div class="ml-4 mb-2 mt-2 d-flex align-items-center justify-content-start">
            Registro Nº _________________
        </div>

        <div class="mx-4">
            <div class="d-flex flex-column flex-nowrap border border-dark rounded overflow-hidden">
                <div class="border border-dark text-center">
                    <h6 class="mt-1">
                        assistência médica sanitária
                    </h6>
                </div>

                <div class="p-2">
                    <div class="d-flex">
                        <span class="font-weight-bold">Nome:</span><span id="nome" class="flex-grow-1 mx-2"
                            style="border-bottom: 1px solid black; display: inline-block; padding-left:10px">Nome:</span>
                    </div>

                    <div class="d-flex mt-2">
                        <span class="font-weight-bold">Nome do pai:</span><span id="nome_pai" class="flex-grow-1 mx-2"
                            style="border-bottom: 1px solid black; display: inline-block; padding-left:10px"></span>
                    </div>

                    <div class="d-flex mt-2">
                        <span class="font-weight-bold">Nome da mae:</span><span id="nome_mae" class="flex-grow-1 mx-2"
                            style="border-bottom: 1px solid black; display: inline-block; padding-left:10px"></span>
                    </div>

                    <div class="row mt-2">
                        <div class="col-8">
                            <div class="d-flex flex-nowrap">
                                <span class="font-weight-bold">Naturalidade:</span><span id="naturalidade"
                                    class="flex-grow-1 ml-2"
                                    style="border-bottom: 1px solid black; display: inline-block; padding-left:10px">Obidos-pa</span>
                            </div>
                        </div>

                        <div class="col-4">
                            <div class="d-flex flex-nowrap">
                                <span class="font-weight-bold">Sexo:</span><span id="sexo" class="flex-grow-1 mx-2"
                                    style="border-bottom: 1px solid black; display: inline-block; padding-left:10px">Feminino</span>
                            </div>
                        </div>
                    </div>


                    <div class="d-flex mt-2">
                        <span class="font-weight-bold">Data de Nascimento:</span><span id="nascimento"
                            class="flex-grow-1 mx-2"
                            style="border-bottom: 1px solid black; display: inline-block; padding-left:10px">12/05/90</span>

                        <span class="font-weight-bold">Idade:</span><span id="idade" class="flex-grow-1 mx-2"
                            style="border-bottom: 1px solid black; display: inline-block; padding-left:10px">30 Anos</span>
                    </div>


                    <div class="d-flex mt-2">
                        <span class="font-weight-bold">Telefone:</span><span id="telefone" class="flex-grow-1 mx-2"
                            style="border-bottom: 1px solid black; display: inline-block; padding-left:10px">32332323</span>

                        <span class="font-weight-bold">Sus:</span><span id="sus" class="flex-grow-1 mx-2"
                            style="border-bottom: 1px solid black; display: inline-block; padding-left:10px">2589965666622365</span>
                    </div>


                    <div class="d-flex mt-2">
                        <span class="font-weight-bold">Estado Civil:</span><span id="estado_civil" class="flex-grow-1 mx-2"
                            style="border-bottom: 1px solid black; display: inline-block; padding-left:10px">Casada</span>

                        <span class="font-weight-bold">Profissão:</span><span id="profissao" class="flex-grow-1 mx-2"
                            style="border-bottom: 1px solid black; display: inline-block; padding-left:10px">Marceneiro</span>
                    </div>

                    <div class="mt-2">
                        <div style="float: left;" class="pr-2 bg-light font-weight-bold">Endereço:</div>
                        <div id="endereco"
                            style="background:url('img/underline_Prancheta 1.png'); background-position:bottom; padding-left:10px; float: none;">
                            _
                        </div>
                    </div>
                </div>
            </div>

            <div class="mt-3 border border-dark rounded overflow-hidden" style="height: 150px">
                <div class="border border-dark text-center">
                    <h6 class="mt-1">
                        História Clínica
                    </h6>
                </div>
                <div class="d-flex flex-column justify-content-center">
                    <span>Queixa principal:</span>
                    <span>H. Doença Atual:</span>
                    <span>Dor Torácica: </span>
                    <span>H. Doença Atual:</span>
                </div>
            </div>

            <div class="mt-3 border border-dark rounded" style="height: 150px">

            </div>

            <div class=" mt-2 text-center">
                <span>Prontuário aberto dia: </span><span>25/13/2021</span> <span>pelo funcionário </span><span>Fulano
                    de tal</span>
            </div>
        </div>

    </div>
</div>