<!DOCTYPE html>

<html lang="pt-br">



<head>

    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Agendamento Consultas - CF</title>

    <link rel="stylesheet" href="css/evo-calendar.css" type="text/css" />
    <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" type="text/css" href="css/all.min.css" />
    <link rel="stylesheet" type="text/css" href="css/chart.min.css">
    <link rel="stylesheet" type="text/css" href="css/spectrum.min.css">
    <link rel="stylesheet" type="text/css" href="css/style.css" />
    <script src="js/cleave.min.js"></script>
    <script src="js/htm2canvas.js"></script> <!--gerar PDF-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.4.1/jspdf.debug.js" integrity="sha384-THVO/sM0mFD9h7dfSndI6TS0PgAGavwKvB5hAxRRvc0o9cPLohB0wb/PTA7LdUHs" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/Chart.min.js"></script>
    <script src="js/Chart.bundle.min.js"></script>
</head>



<body>

<div class="allButFooter">

    <?= $this->content()?>
</div>



    <?php if(isset($_SESSION['nome'])){?>

    <footer class="bg-primary text-center text-white mt-4 p-4">

    &#169; Aplicação desenvolvida por <br> Paulo Vinícius Ribeiro Monteiro - 2021

    </footer>

    <?php }?>

    <script src="js/spectrum.min.js"></script> <!--cores dos gráficos-->
    <script type="text/javascript" src="../js/evo-calendar.min.js"></script>
    <script type="text/javascript" src="../js/ajustesCalendario.js"></script>



</body>



</html>