name: Deploy to Hostinger

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install Composer dependencies
      run: |
        cd app_agendamento
        composer install --no-dev --optimize-autoloader

    - name: Deploy to Hostinger
      env:
        H_HOST: ${{ secrets.HOSTINGER_SSH_HOST }}
        H_USER: ${{ secrets.HOSTINGER_SSH_USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        H_DIR: '/home/seu_usuario/public_html/seu_projeto'  # Caminho do seu projeto na Hostinger
      run: |
          # Criar o diretório .ssh
          mkdir -p ~/.ssh
          
          # Colocar a chave privada no arquivo
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Adicionar o host à lista de conhecidos
          ssh-keyscan -H ${H_HOST%%:*} >> ~/.ssh/known_hosts

          # Verificar variáveis de ambiente
          echo "H_HOST: $H_HOST"
          echo "H_USER: $H_USER"
          echo "H_DIR: $H_DIR"

          echo "Sincronizar arquivos com rsync"
          rsync -avz --delete -e "ssh -p ${H_HOST##*:}" ./app_agendamento/ $H_USER@${H_HOST%%:*}:$H_DIR/ -vv
