name: Deploy to Hostinger

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install Composer dependencies
      run: |
        cd app_agendamento
        composer install --no-dev --optimize-autoloader

    - name: Deploy to Hostinger
      uses: easingthemes/ssh-deploy@main
      with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-rlgoDzvc -i --delete"
            SOURCE: "app_agendamento/"
            REMOTE_HOST: ${{ secrets.HOSTINGER_SSH_HOST }}
            REMOTE_PORT: ${{ secrets.HOSTINGER_SSH_PORT }}
            REMOTE_USER: ${{ secrets.HOSTINGER_SSH_USERNAME }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
